// This file is auto-generated by @hey-api/openapi-ts

export const ApplicationCreateSchema = {
    properties: {
        job_id: {
            type: 'string',
            format: 'uuid',
            title: 'Job Id'
        }
    },
    type: 'object',
    required: ['job_id'],
    title: 'ApplicationCreate'
} as const;

export const ApplicationEventPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        event_type: {
            type: 'string',
            title: 'Event Type'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'event_type', 'message', 'created_at'],
    title: 'ApplicationEventPublic'
} as const;

export const ApplicationFieldPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        field_name: {
            type: 'string',
            title: 'Field Name'
        },
        normalized_key: {
            type: 'string',
            title: 'Normalized Key'
        },
        field_type: {
            type: 'string',
            title: 'Field Type'
        },
        options: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Options'
        },
        value: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Value'
        },
        is_required: {
            type: 'boolean',
            title: 'Is Required'
        },
        resolved: {
            type: 'boolean',
            title: 'Resolved'
        }
    },
    type: 'object',
    required: ['id', 'field_name', 'normalized_key', 'field_type', 'options', 'value', 'is_required', 'resolved'],
    title: 'ApplicationFieldPublic'
} as const;

export const ApplicationPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        job_id: {
            type: 'string',
            format: 'uuid',
            title: 'Job Id'
        },
        job: {
            '$ref': '#/components/schemas/JobShortPublic'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'job_id', 'job', 'status', 'created_at', 'updated_at'],
    title: 'ApplicationPublic'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const Body_resumes_upload_resumeSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_resumes-upload_resume'
} as const;

export const FieldResolveInputSchema = {
    properties: {
        field_id: {
            type: 'string',
            format: 'uuid',
            title: 'Field Id'
        },
        value: {
            type: 'string',
            title: 'Value'
        }
    },
    type: 'object',
    required: ['field_id', 'value'],
    title: 'FieldResolveInput'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const JobMatchPublicSchema = {
    properties: {
        job: {
            '$ref': '#/components/schemas/JobPublic'
        },
        score: {
            type: 'number',
            title: 'Score'
        }
    },
    type: 'object',
    required: ['job', 'score'],
    title: 'JobMatchPublic'
} as const;

export const JobPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        company: {
            type: 'string',
            title: 'Company'
        },
        location: {
            type: 'string',
            title: 'Location'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        url: {
            type: 'string',
            title: 'Url'
        },
        ats_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ats Type'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'title', 'company', 'location', 'description', 'url', 'ats_type', 'created_at'],
    title: 'JobPublic'
} as const;

export const JobShortPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        company: {
            type: 'string',
            title: 'Company'
        },
        location: {
            type: 'string',
            title: 'Location'
        }
    },
    type: 'object',
    required: ['id', 'title', 'company', 'location'],
    title: 'JobShortPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ProfilePublicSchema = {
    properties: {
        personal_info: {
            additionalProperties: true,
            type: 'object',
            title: 'Personal Info'
        },
        education: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Education'
        },
        experience: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Experience'
        },
        skills: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Skills'
        },
        portfolio_links: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Portfolio Links'
        },
        preferences: {
            additionalProperties: true,
            type: 'object',
            title: 'Preferences'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'created_at', 'updated_at'],
    title: 'ProfilePublic'
} as const;

export const ProfileUpdateSchema = {
    properties: {
        personal_info: {
            additionalProperties: true,
            type: 'object',
            title: 'Personal Info'
        },
        education: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Education'
        },
        experience: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Experience'
        },
        skills: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Skills'
        },
        portfolio_links: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Portfolio Links'
        },
        preferences: {
            additionalProperties: true,
            type: 'object',
            title: 'Preferences'
        }
    },
    type: 'object',
    title: 'ProfileUpdate'
} as const;

export const QuestionMatchRequestSchema = {
    properties: {
        question: {
            type: 'string',
            title: 'Question'
        }
    },
    type: 'object',
    required: ['question'],
    title: 'QuestionMatchRequest'
} as const;

export const QuestionMatchResponseSchema = {
    properties: {
        matched: {
            type: 'boolean',
            title: 'Matched'
        },
        answer: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Answer'
        }
    },
    type: 'object',
    required: ['matched', 'answer'],
    title: 'QuestionMatchResponse'
} as const;

export const QuestionMemoryCreateSchema = {
    properties: {
        question: {
            type: 'string',
            title: 'Question'
        },
        normalized_key: {
            type: 'string',
            title: 'Normalized Key'
        },
        answer: {
            type: 'string',
            title: 'Answer'
        }
    },
    type: 'object',
    required: ['question', 'normalized_key', 'answer'],
    title: 'QuestionMemoryCreate'
} as const;

export const QuestionMemoryPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        question: {
            type: 'string',
            title: 'Question'
        },
        normalized_key: {
            type: 'string',
            title: 'Normalized Key'
        },
        answer: {
            type: 'string',
            title: 'Answer'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'question', 'normalized_key', 'answer', 'created_at'],
    title: 'QuestionMemoryPublic'
} as const;

export const ResumePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        filename: {
            type: 'string',
            title: 'Filename'
        },
        file_path: {
            type: 'string',
            title: 'File Path'
        },
        parsed_data: {
            additionalProperties: true,
            type: 'object',
            title: 'Parsed Data'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'filename', 'file_path', 'parsed_data', 'created_at'],
    title: 'ResumePublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;