// This file is auto-generated by @hey-api/openapi-ts

export type ApplicationCreate = {
    job_id: string;
};

export type ApplicationEventPublic = {
    id: string;
    event_type: string;
    message: string;
    created_at: string;
};

export type ApplicationFieldPublic = {
    id: string;
    field_name: string;
    normalized_key: string;
    field_type: string;
    options: Array<{
        [key: string]: unknown;
    }>;
    value: (string | null);
    is_required: boolean;
    resolved: boolean;
};

export type ApplicationPublic = {
    id: string;
    job_id: string;
    job: JobShortPublic;
    status: string;
    created_at: string;
    updated_at: string;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_resumes_upload_resume = {
    file: (Blob | File);
};

export type FieldResolveInput = {
    field_id: string;
    value: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type JobMatchPublic = {
    job: JobPublic;
    score: number;
};

export type JobPublic = {
    id: string;
    title: string;
    company: string;
    location: string;
    description: string;
    url: string;
    ats_type: (string | null);
    created_at: string;
};

export type JobShortPublic = {
    id: string;
    title: string;
    company: string;
    location: string;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProfilePublic = {
    personal_info?: {
        [key: string]: unknown;
    };
    education?: Array<{
        [key: string]: unknown;
    }>;
    experience?: Array<{
        [key: string]: unknown;
    }>;
    skills?: Array<(string)>;
    portfolio_links?: Array<{
        [key: string]: unknown;
    }>;
    preferences?: {
        [key: string]: unknown;
    };
    id: string;
    user_id: string;
    created_at: string;
    updated_at: string;
};

export type ProfileUpdate = {
    personal_info?: {
        [key: string]: unknown;
    };
    education?: Array<{
        [key: string]: unknown;
    }>;
    experience?: Array<{
        [key: string]: unknown;
    }>;
    skills?: Array<(string)>;
    portfolio_links?: Array<{
        [key: string]: unknown;
    }>;
    preferences?: {
        [key: string]: unknown;
    };
};

export type QuestionMatchRequest = {
    question: string;
};

export type QuestionMatchResponse = {
    matched: boolean;
    answer: (string | null);
};

export type QuestionMemoryCreate = {
    question: string;
    normalized_key: string;
    answer: string;
};

export type QuestionMemoryPublic = {
    id: string;
    question: string;
    normalized_key: string;
    answer: string;
    created_at: string;
};

export type ResumePublic = {
    id: string;
    filename: string;
    file_path: string;
    parsed_data: {
        [key: string]: unknown;
    };
    created_at: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ApplicationsListApplicationsResponse = (Array<ApplicationPublic>);

export type ApplicationsCreateApplicationData = {
    requestBody: ApplicationCreate;
};

export type ApplicationsCreateApplicationResponse = (ApplicationPublic);

export type ApplicationsStartApplyingData = {
    appId: string;
};

export type ApplicationsStartApplyingResponse = (unknown);

export type ApplicationsGetApplicationFieldsData = {
    appId: string;
};

export type ApplicationsGetApplicationFieldsResponse = (Array<ApplicationFieldPublic>);

export type ApplicationsResolveApplicationFieldsData = {
    appId: string;
    requestBody: Array<FieldResolveInput>;
};

export type ApplicationsResolveApplicationFieldsResponse = (unknown);

export type ApplicationsSubmitJobApplicationData = {
    appId: string;
};

export type ApplicationsSubmitJobApplicationResponse = (unknown);

export type ApplicationsGetApplicationEventsData = {
    appId: string;
};

export type ApplicationsGetApplicationEventsResponse = (Array<ApplicationEventPublic>);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type JobsListJobsResponse = (Array<JobPublic>);

export type JobsDiscoverNewJobsResponse = (Array<JobPublic>);

export type JobsGetMatchedJobsResponse = (Array<JobMatchPublic>);

export type JobsGetJobData = {
    jobId: string;
};

export type JobsGetJobResponse = (JobPublic);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProfileGetMyProfileResponse = (ProfilePublic);

export type ProfileUpdateMyProfileData = {
    requestBody: ProfileUpdate;
};

export type ProfileUpdateMyProfileResponse = (ProfilePublic);

export type QuestionsListQuestionsResponse = (Array<QuestionMemoryPublic>);

export type QuestionsSaveQuestionAnswerData = {
    requestBody: QuestionMemoryCreate;
};

export type QuestionsSaveQuestionAnswerResponse = (QuestionMemoryPublic);

export type QuestionsMatchQuestionData = {
    requestBody: QuestionMatchRequest;
};

export type QuestionsMatchQuestionResponse = (QuestionMatchResponse);

export type ResumesUploadResumeData = {
    formData: Body_resumes_upload_resume;
};

export type ResumesUploadResumeResponse = (ResumePublic);

export type ResumesListResumesResponse = (Array<ResumePublic>);

export type ResumesGetResumeData = {
    resumeId: string;
};

export type ResumesGetResumeResponse = (ResumePublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);