"""Add selector to application field

Revision ID: 3b044aaafe09
Revises: 9c6c14937e88
Create Date: 2026-06-07 23:06:23.049442

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3b044aaafe09'
down_revision = '9c6c14937e88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicationfield', sa.Column('selector', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applicationfield', 'selector')
    # ### end Alembic commands ###
