"""Add job application automation models

Revision ID: 9c6c14937e88
Revises: fe56fa70289e
Create Date: 2026-06-07 22:56:41.950429

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9c6c14937e88'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('ats_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_company'), 'job', ['company'], unique=False)
    op.create_index(op.f('ix_job_title'), 'job', ['title'], unique=False)
    op.create_index(op.f('ix_job_url'), 'job', ['url'], unique=True)
    op.create_table('application',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_job_id'), 'application', ['job_id'], unique=False)
    op.create_index(op.f('ix_application_status'), 'application', ['status'], unique=False)
    op.create_index(op.f('ix_application_user_id'), 'application', ['user_id'], unique=False)
    op.create_table('profile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('personal_info', sa.JSON(), nullable=False),
    sa.Column('education', sa.JSON(), nullable=False),
    sa.Column('experience', sa.JSON(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('portfolio_links', sa.JSON(), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_user_id'), 'profile', ['user_id'], unique=True)
    op.create_table('questionmemory',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalized_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questionmemory_normalized_key'), 'questionmemory', ['normalized_key'], unique=False)
    op.create_index(op.f('ix_questionmemory_question'), 'questionmemory', ['question'], unique=False)
    op.create_index(op.f('ix_questionmemory_user_id'), 'questionmemory', ['user_id'], unique=False)
    op.create_table('resume',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('raw_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parsed_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_user_id'), 'resume', ['user_id'], unique=False)
    op.create_table('applicationevent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applicationevent_application_id'), 'applicationevent', ['application_id'], unique=False)
    op.create_table('applicationfield',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('normalized_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('field_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applicationfield_application_id'), 'applicationfield', ['application_id'], unique=False)
    op.create_index(op.f('ix_applicationfield_normalized_key'), 'applicationfield', ['normalized_key'], unique=False)
    op.create_index(op.f('ix_applicationfield_resolved'), 'applicationfield', ['resolved'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applicationfield_resolved'), table_name='applicationfield')
    op.drop_index(op.f('ix_applicationfield_normalized_key'), table_name='applicationfield')
    op.drop_index(op.f('ix_applicationfield_application_id'), table_name='applicationfield')
    op.drop_table('applicationfield')
    op.drop_index(op.f('ix_applicationevent_application_id'), table_name='applicationevent')
    op.drop_table('applicationevent')
    op.drop_index(op.f('ix_resume_user_id'), table_name='resume')
    op.drop_table('resume')
    op.drop_index(op.f('ix_questionmemory_user_id'), table_name='questionmemory')
    op.drop_index(op.f('ix_questionmemory_question'), table_name='questionmemory')
    op.drop_index(op.f('ix_questionmemory_normalized_key'), table_name='questionmemory')
    op.drop_table('questionmemory')
    op.drop_index(op.f('ix_profile_user_id'), table_name='profile')
    op.drop_table('profile')
    op.drop_index(op.f('ix_application_user_id'), table_name='application')
    op.drop_index(op.f('ix_application_status'), table_name='application')
    op.drop_index(op.f('ix_application_job_id'), table_name='application')
    op.drop_table('application')
    op.drop_index(op.f('ix_job_url'), table_name='job')
    op.drop_index(op.f('ix_job_title'), table_name='job')
    op.drop_index(op.f('ix_job_company'), table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###
